# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch
tensor_a = torch.rand((7, 7))
print(tensor_a)
print("Shape: ",tensor_a.shape)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
import torch
tensor_b = torch.rand((1, 7))
print(tensor_b)
print('shape:', tensor_b.shape)
result = torch.matmul(tensor_a, tensor_b.T)
print(result)

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
import torch
torch.manual_seed(0)
tensor_a = torch.rand((7,7))
tensor_b = torch.rand((1,7))
print('tensor_a:', tensor_a)
print('tensor_b:', tensor_b)
result = tensor_a @ tensor_b.T
print('result:', result)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
import torch
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(1234)
    print('Set CUDA manual seed to 1234')
else:
    print('CUDA not available on this machine')


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor_A = torch.rand((2,3), device=device)
tensor_B = torch.rand((2,3), device=device)
print('tensor_A:', tensor_A)
print('tensor_B:', tensor_B)
print('tensor_A shape:', tensor_A.shape, 'device:', tensor_A.device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
result = tensor_A @ tensor_B.T
print('result:', result)
print('result shape:', result.shape)

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
max_val = result.max()
min_val = result.min()
print('max value:', max_val.item())
print('min value:', min_val.item())

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
flat_argmax = result.view(-1).argmax()
flat_argmin = result.view(-1).argmin()
argmax_2d = (flat_argmax // result.shape[1], flat_argmax % result.shape[1])
argmin_2d = (flat_argmin // result.shape[1], flat_argmin % result.shape[1])
print('flat argmax index:', flat_argmax.item(), 'as 2D index:', argmax_2d)
print('flat argmin index:', flat_argmin.item(), 'as 2D index:', argmin_2d)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
import torch
torch.manual_seed(0)
tensor = torch.rand((1,1,1,10))
print(tensor, tensor.shape)
squeezed = tensor.squeeze() 
print(squeezed, squeezed.shape)